import os
import subprocess
cwd = os.getcwd()
program = cwd + "/text_microservice.py"

#PROGRAM CODE
#PROGRAM CODE
#PROGRAM CODE

#Call to Microservice

result = subprocess.run(["python", program, "example.txt", "True"], capture_output=True, text=True)
print(result.stdout.strip())

#Program reads the text file generated by microservice.

# REST OF PROGRAM
# REST OF PROGRAM
# REST OF PROGRAM
# REST OF PROGRAM
# REST OF PROGRAM
